### ISSUE TITLE
Fix a DNS issue when running che-server on OpenShift

### ISSUE THREAD

**Issue by l0rd** [l0rd/openche#4]
At startup Che returns the following error:

```
2016-10-18 10:30:50,167[ted-scheduler-0]  [ERROR] [a.d.WsMasterAnalyticsAddresser 37]   - Failed to send master analytics
java.net.UnknownHostException: install.codenvycorp.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_101]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_101]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_101]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_101]
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[na:1.8.0_101]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_101]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_101]
```

The host install.codenvycorp.com cannot be resolved.

Containers /etc/resolv.conf

```
search eclipse-che.svc.cluster.local svc.cluster.local cluster.local vm
nameserver 10.0.2.15
nameserver 10.0.2.3
options ndots:5
```

VM /etc/resolv.conf

```
# Generated by NetworkManager
search vm
nameserver 10.0.2.3
```

**Comment by l0rd** [comment]
Probably related to https://github.com/kubernetes/kubernetes/issues/33554

**Comment by l0rd** [comment]
Another workaround that uses ConfigMaps: https://github.com/kubernetes/kubernetes/pull/35525#issuecomment-257919311
